### ISSUE TITLE
KTLint Action finishing with success event when has erros

### ISSUE THREAD

**Issue by faogustavo** [ScaCap/action-ktlint#1]
I want to finish the job with and error if I found some error on lint, but, event with errors, the returning code is being successful.

I believe that the returning code from the script is from the "reviewdog" with a successful report. 

![image](https://user-images.githubusercontent.com/7588480/77918213-f1b0fb00-7271-11ea-87db-f72831cc8c52.png)

**Comment by renatoabreu11** [comment]
Hey @faogustavo,

Could you provide a small example to replicate this behavior? Thanks.

**Comment by faogustavo** [comment]
My workflow job is configure like this 👇 

```yml
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
```

And I've put in a file, a ktlint error. In my case I used a wildcard import.

And then, after the job runs, I was expecting that it would fail with an error (as I have a lint error), but it continued with a success.

I found that the problem is cause by the report action (reviewdog). As it runs lastly, it's code is used to identify if the job succeeded or not. (and as it succeeded to add the message to PR, it returns 0)

The solution is quite simple, you just have to add a `pipefail` flag to your script. It will return the last error code greater than zero on the rightmost position, in this case, from the KTLint. For more informations, [check this link](https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/#set-o-pipefail).
