### ISSUE TITLE
Running kt-lint on self-hosted

### ISSUE THREAD

**Issue by bhavik-lfc** [ScaCap/action-ktlint#13]
I have run reviewdog with fastlane on ubuntu-latest and it works perfect.

When I run it on self-hosted It gives me below error

![image](https://user-images.githubusercontent.com/59360119/95590111-47593200-0a63-11eb-8f88-2fdb8f3135ed.png)

This is my yml file

```yml
lintCheck:
    name: Lint Check
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install Dependencies
        run: gem install bundler && bundle install
      - name: Lint
        run: bundle exec fastlane lint
      - name: Run Android Lint
        uses: dvdandroid/action-android-lint@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          lint_xml_file: app/build/reports/lint-results.xml
```
Any Ideas what could be the reason?
