### ISSUE TITLE
Task fails even when no lint errors

### ISSUE THREAD

**Issue by sjjctl** [ScaCap/action-ktlint#24]
it was working when i tested it with errors, it detects them and leaves comments

But even setting level: warning or level: info, it didn't fix it.

I have fail_on_error: true, but there were no errors to fail on?  Logs don't provide much on the surface

```
Run ScaCap/action-ktlint@1.3
  with:
    github_token: ***
    reporter: github-pr-review
    fail_on_error: true
    level: info
    relative: true
    android: false
/usr/bin/docker run --name d8a[2](https://github.com/CenturyLinkCloud/as-storagefabric-middle-tier/runs/6425000286?check_suite_focus=true#step:4:2)1abc4f6004[3](https://github.com/CenturyLinkCloud/as-storagefabric-middle-tier/runs/6425000286?check_suite_focus=true#step:4:3)a3a3a88da828d018[4](https://github.com/CenturyLinkCloud/as-storagefabric-middle-tier/runs/6425000286?check_suite_focus=true#step:4:4)4_f1816f --label 084[5](https://github.com/CenturyLinkCloud/as-storagefabric-middle-tier/runs/6425000286?check_suite_focus=true#step:4:5)0d --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_REPORTER -e INPUT_FAIL_ON_ERROR -e INPUT_LEVEL -e INPUT_RELATIVE -e INPUT_ANDROID -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/as-storagefabric-middle-tier/as-storagefabric-middle-tier":"/github/workspace" 08450d:8a21abc4f[6](https://github.com/CenturyLinkCloud/as-storagefabric-middle-tier/runs/6425000286?check_suite_focus=true#step:4:6)0043a3a3a[8](https://github.com/CenturyLinkCloud/as-storagefabric-middle-tier/runs/6425000286?check_suite_focus=true#step:4:8)8da828d01844  "***" "info" "github-pr-review" "true" "true" "false"
KtLint version: 0.45.2
```
