### ISSUE TITLE
Reporter reports only one message

### ISSUE THREAD

**Issue by naivekook** [ScaCap/action-ktlint#36]
Hi!
I faced the problem that in output I have a lot of error messages but GitHub bot reports only one.
I'm expecting that if I have 50 ktlint errors it will see 50 PR comments.

Part of output:
![Screenshot 2023-02-22 at 10 14 51](https://user-images.githubusercontent.com/1501831/220575194-68274faf-3fe5-40d3-aaa3-2523f0ecf2cf.png)

GA workflow:
```
name: Code Review Workflow
on: [pull_request]
jobs:
  ktlint:
    name: Check Code Style
    runs-on: [self-hosted, nonroot]

    steps:
      - uses: actions/checkout@v3
      - uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: file

```
