### ISSUE TITLE
no errors and vroy/gha-kotlin-linter shows about 3000+ on a repo

### ISSUE THREAD

**Issue by gvasquez95** [ScaCap/action-ktlint#6]
workflow defined as follows:

```
# This is a basic workflow to help you get started with Actions


name: reviewdog

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: ktlint
      uses: ScaCap/action-ktlint@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review # Change reporter

    - name: Kotlin Linter
      uses: vroy/gha-kotlin-linter@v2
```
